### ISSUE TITLE
Compost Bin Crash

### ISSUE THREAD

**Issue by WesCook** [GlobbyPotato/Rockhounding_Surface#1]
The Compost Bin will immediately crash when any items are added to its inventory.

https://pastebin.com/PnFizruc

Rockhounding Core: 1.10.2-1.09
Rockhounding Surface: 1.10.2-1.23
Forge: 12.18.3.2422
Minecraft: 1.10.2

I have not tested the newer 1.11 build.

**Comment by GlobbyPotato** [comment]
Found it. It's a compatibility issue if Natura is not installed. Will fix it asap for both mc versions, sorry for the issue.
