### ISSUE TITLE
Truffles recipes in the Compost Bin 

### ISSUE THREAD

**Issue by cScotPlay** [GlobbyPotato/Rockhounding_Surface#10]
Surface Version: 3.12
Core Version: 3.17

Issue:  When the Truffles are disabled in the config file they still show up in the Compost Bin as a recipe for Organic Compost.  The truffles appear to not be registered as they are showing up with the lovely purple and black texture pattern.  Is it possible to get the truffles removed from the Compost Bin when they are disabled in the config files?

Thanks,
Scot

**Comment by GlobbyPotato** [comment]
Fixed, those recipes fell off the enabler check.
