### ISSUE TITLE
Plants not breaking

### ISSUE THREAD

**Issue by cScotPlay** [GlobbyPotato/Rockhounding_Surface#11]
Surface Version: 3.12
Core Version: 3.17

When the block underneath the following plants are broken the plants stay intact.  This is not the case for Short Grass or the Skunkbush.

Indian Ricegrass
Soaptree Yukka
Desert Spoon
Purple Prickly Pear
Honey Mesquite 
Tall Grass

It causes some weird floating plants in world generation when the White Sand falls.

**Comment by GlobbyPotato** [comment]
It should be fixed now, The neighbour check went wrong in the previous alpha.
Thanks for reporting.
