### ISSUE TITLE
[1.12.2] Crash on startup with newest Rockhounding: Chemistry

### ISSUE THREAD

**Issue by ToMe25** [GlobbyPotato/Rockhounding_Surface#14]
Trying to Start Minecraft with the latest Rockhounding Surface and Chemistry Crashes the Game whilst starting.

Crash Report: [crash-2019-06-09_09.54.24-client.txt](https://github.com/GlobbyPotato/Rockhounding_Surface/files/3269342/crash-2019-06-09_09.54.24-client.txt)

Used Mod Versions:
Rockhounding: Core: 3.22
Rockhounding: Surface: 3.11
CodeChickenLib: 3.2.2.353
Redstone Flux: 2.1.0.6
Bookshelf: 2.3.581
Guidebook: 2.9.1
Rockhoudning: Chemistry: 3.42

**Comment by GlobbyPotato** [comment]
Sorry for the delay, never got notified anywhere of this issue open. Will give it a look, meantime make sure you have all the latest version of all the RH modules, in case it was something added later.

**Comment by ToMe25** [comment]
OK last time i tried it with the newest release versions, this time i tried with the newest versions including beta ones and it didn't crashed.
