### ISSUE TITLE
[1.12.2] [Request] Biome generation blacklist for each fossil wood

### ISSUE THREAD

**Issue by NotAVerb** [GlobbyPotato/Rockhounding_Surface#4]
I want to disable the bog spruce from generating in meadows without completely disabling bog spruce generation.

**Comment by GlobbyPotato** [comment]
I'm rearranging a little the generation to keep them the closest to their environment. 
A blacklist for each wood would be too much gen computing for too little result and I'm already filtering them. The generation depends on the types the biomes are registered on. Multiple tags may occasionally cause some wood appear in a place not really visually fitting.
