### ISSUE TITLE
Ore dictionary for blocks and items

### ISSUE THREAD

**Issue by KorDum** [GlobbyPotato/Rockhounding_Surface#6]
Sticks are missing "stickWood" ore dictionary.
Planks are missing "plankWood".
Fences are missing "fenceWood".
Fence Gates are missing "fenceGateWood".
Stairs are missing "stairWood".
Slabs are missing "slabWood".
Logs are missing "logWood".

**Comment by GlobbyPotato** [comment]
There is a config value to enable them:

    # Wheter the wood parts will be oredicted for common uses
    B:WOOD_OREDICT=false

**Comment by KorDum** [comment]
Thanks!
