### ISSUE TITLE
[Request] Ore Dic support

### ISSUE THREAD

**Issue by judicius** [GlobbyPotato/Rockhounding_Surface#7]
Is there any way to provide oredic support for white sand so that it is oredic with say Biomes o Plenty white sand?

Forge Version: 14.23.4.2707
Rockhounding Version: 1.12.2-3.08

**Comment by GlobbyPotato** [comment]
I don't know yet if they oredicted their sand. You can eventually use CraftTweaker to register both with the same key:

`val white_sand_dict = <ore:whiteSand>;`
`white_sand_dict.addItems([<rockhounding_surface:white_sand>, <biomesoplenty:white_sand>]);`
