### ISSUE TITLE
Drops from logs are incorrect

### ISSUE THREAD

**Issue by brisingraerowing** [GlobbyPotato/Rockhounding_Surface#9]
All logs only drop logs with a data value of 0 from their respective sets (e.g. Teredo-Bored Wood drops Fossil Azurite Wood).

This may be a conflict with another mod I have. I'll do some more testing to figure that out.

RH Surface: 3.11
RH Core: 3.16
Forge: 2772
MC: 1.12.2

**Comment by GlobbyPotato** [comment]
I didn't noticed any error like this, wood is dropping correctly when using regular tools.

**Comment by brisingraerowing** [comment]
It seems to be a compat issue with a mod I was using. I'm not seeing it now either.
